name: Publish Docker and PyPi
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Get Version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: python publish_to_DockerHub.py
        
      - name: Build and push PyPI Package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: python publish_to_PyPI.py

        
  
